services:
  - type: web
    name: vivienda-esp-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      